var screenWidth = screen.availWidth,
    vpWidth = screenWidth,
    screenHeight = screen.availHeight,
    vpHeight = screenHeight,
    vpX,
    vpY,
    deadend,
    selectedAircraft,
    onOffKnob,
    g,
    svgOnOffKnob,
    svgOffKnob,
    svgOnOffKnobCx,
    svgOnOffKnobCy,
    mainMenu,
    lblMainMenu,
    optMrh90,
    optMh60r,
    optS70a9,
    optCh47f,
    aircraftSholMenu, // group
    optionsTopAircraftSholSelect, // group
    optMenuAircraftSholSelect,
    lblMainMenuAircraftSholSelect,
    optAircraftSholsSelect,
    optBridgeEmergencyCards,
    optFlycoEmergencyChecklists,
    optFlycoStandardChecklists,
    optArhTiger,
    optForeign,
    activeSholDisplay, // group
    optionsBottom, // group
    optCda,
    opt6,
    opt5,
    opt4,
    opt3,
    opt2,
    opt1,
    optCdf,
    hilightCda,
    hilight6,
    hilight5,
    hilight4,
    hilight3,
    hilight2,
    hilight1,
    hilightCdf,
    optionsTop, // group
    lblAircraftId, // group
    optAircraftIdIndicator,
    optAircraftIdHighlight,
    optXfer,
    optVertrep,
    optLand,
    optLaunch,
    optTaxi,
    optEngageShutdown, // group
    txtShutdown,
    txtEngage,
    hilightXfer,
    hilightVertrep,
    hilightLand,
    hilightLaunch,
    hilightTaxi,
    hilightEngageShutdown, // group
    optMenu,
    lblAircraft, // group
    optAircraftIndicator,
    optHighlight,
    optionsLeft, // group
    optIntoWind,
    optAft,
    optFwd,
    optNight,
    optDay,
    optBack,
    hilightIntoWind,
    hilightAft,
    hilightFwd,
    hilightNight,
    hilightDay,
    polarGraph, // group
    anglesKnotsLabels, // group
    g160,
    g140,
    g120,
    g100,
    g80,
    g60,
    g40,
    g20,
    r160,
    r140,
    r120,
    r100,
    r80,
    r60,
    r40,
    r20,
    knotsLabels, // group
    polarGridLines, // group
    redGreenCircle, // group

    // pitch and roll indicators
    pitchIndicators, // group
    pitchGraph, // group
    pitchDownMax1,
    pitchDownMax15,
    pitchDownMax2,
    pitchDownMax3,
    pitchDownMax4,
    pitchDownMax5,
    lastPitchDownPosIndicator,
    pitchBarIndicator,
    lastPitchUpPosIndicator,
    pitchUpMax1,
    pitchUpMax15,
    pitchUpMax2,
    pitchUpMax3,
    pitchUpMax4,
    rollIndicators,
    rollGraph,
    rollPortMax1,
    rollPortMax15,
    rollPortMax2,
    rollPortMax3,
    rollPortMax4,
    lastRollPortIndicator,
    rollBarIndicator,
    lastRollStarboardIndicator,
    rollStarboardMax1,
    rollStarboardMax15,
    rollStarboardMax2,
    rollStarboardMax3,
    rollStarboardMax4,
    // -----------------------
    optionsRight, // group
    display,
    onOffKnob, // group
    onOffKnobIndicator,
    onOffKnobHighlight,
    onOffKnobFace,
    onOffKnobShadow,
    buttonsTop,
    btnSpareTop, // group
    lightSpare,
    lightOutlineSpareTop,
    gradientSpareTop,
    faceSpareTop,
    btnXfer, // group
    lightXfer,
    lightOutlineXfer,
    gradientXfer,
    faceXfer,
    btnVertrep, // group
    lightVertrep,
    lightOutlineVertrep,
    gradientVertrep,
    faceVertrep,
    btnLand, // group
    lightLand,
    lightOutlineLand,
    gradientLand,
    faceLand,
    btnLaunch, // group
    lightLaunch,
    lightOutlineLaunch,
    gradientLaunch,
    faceLaunch,
    btnTaxi, // group
    lightTaxi,
    lightOutlineTaxi,
    gradientTaxi,
    faceTaxi,
    btnEngageShutdown, // group
    lightEngageShutdown,
    lightOutlineEngageShutdown,
    gradientEngageShutdown,
    faceEngageShutdown,
    btnMenu, // group
    lightMenuActiveDisplay,
    lightOutlineMenuActiveDisplay,
    gradientMenuActiveDisplay,
    faceMenuActiveDisplay,
    buttonsBottom,
    btnCdf, // group
    lightCdf,
    lightOutlineCdf,
    gradientCdf,
    faceCdf,
    btn1,
    light1,
    lightOutline1,
    gradient1,
    face1,
    btn2,
    light2,
    lightOutline2,
    gradient2,
    face2,
    btn3,
    light3,
    lightOutline3,
    gradient3,
    face3,
    btn4,
    light4,
    lightOutline4,
    gradient4,
    face4,
    btn5,
    light5,
    lightOutline5,
    gradient5,
    face5,
    btn6,
    light6,
    lightOutline6,
    gradient6,
    face6,
    btnCda,
    lightCda,
    lightOutlineCda,
    gradientCda,
    faceCda,
    buttonsRight, // group
    btnEmergency, // group
    lightEmergency,
    lightOutlineEmergency,
    gradientEmergency,
    faceGradientEmergency,
    btnSpareRight, // group
    lightSpareRight,
    lightOutlineSpareRight,
    gradientSpareRight,
    faceSpareRight,
    btnHotHeavy, // group
    lightHotHeavy,
    lightOutlineHotHeavy,
    gradientHotHeavy,
    faceHotHeavy,
    btnHeavy,
    lightHeavy,
    lightOutlineHeavy,
    gradientHeavy,
    faceHeavy,
    btnMedium,
    lightMedium,
    lightOutlineMedium,
    gradientMedium,
    faceMedium,
    btnLight, // group
    lightLight,
    lightOutlineLight,
    gradientLight,
    faceLight,
    buttonsLeft, // group
    btnIntoWind, // group
    lightIntoWind,
    lightOutlineIntoWind,
    gradientIntoWind,
    faceIntoWind,
    btnAft, // group
    lightAft,
    lightOutlineAft,
    gradientAft,
    faceAft,
    btnFwd, // group
    lightFwd,
    lightOutlineFwd,
    gradientFwd,
    faceFwd,
    btnNight, // group
    lightNight,
    lightOutlineNight,
    gradientNight,
    faceNight,
    btnDay, // group
    lightDay,
    lightOutlineDay,
    gradientDay,
    faceDay,
    btnBack, // group
    lightBack,
    lightOutlineBack,
    gradientBack,
    faceBack,
    wholePanel, // group
    panelLightsTop,
    onOffLabel, // group
    panelLightsRight, // group
    panelLightsLeft, // group
    panelLightsBottom, // group
    backPanel, // group
    topInset,
    bottomInset,
    rightInset,
    leftInset,
    outerPanel,
    isDay,
    isNight,
    isFwd,
    isAft,
    isIntoWind,
    isCda,
    is6,
    is5,
    is4,
    is3,
    is2,
    is1,
    isCdf,
    isEngage,
    isTaxi,
    isLaunch,
    isLand,
    isVertrep,
    isXfer,
    isLight,
    isMedium,
    isHeavy,
    isHotHeavy,
    isEmergency,
    selectedAircraft;    // group
var filteredArray = [];
var btnStatus = [
    false, false, false, false, false, false,
    false, false, false, false, false, false,
    false, false, false, false, false, false,
    false, false, false, false, false, false
];

var plot = [
    "id900-spots-1-6",
    "id900cda-day-only",
    "id901-fwd-facing-cda",
    "id901-fwd-facing-1-6",
    "id901-aft-facing-2-6",
    "id902",
    "id911-spot-1-light-medium",
    "id911-spot-1-heavy",
    "id911-spot-1-hot-heavy",
    "id921-light-medium",
    "id921-heavy",
    "id921-hot-heavy",
    "id922-light-medium",
    "id922-heavy",
    "id923-light-medium-heavy",
    "id923-hot-heavy",
    "id951-light-medium-heavy",
    "id951-hot-heavy",
    "id952-light-medium",
    "id952-heavy",
    "id991-light-medium-heavy",
    "id991-hot-heavy",
    "id992",
    "id993",
    "id994"
]
// Aircraft types supposed to be constants
var MRH90 = 'MRH90';
var MH60R = 'MH60R';
var S70A9 = 'S70A9';
var CH47F = 'CH47F';
var ARH_TIGER = 'ARH TIGER';
var FOREIGN = 'FOREIGN';

var ACTIONS = 1;
var WEIGHTS = 2;
var POSITIONS = 3;
var DIRECTIONS = 4;
var TIMES = 5;
